### ISSUE TITLE
BUG：跨越校区移动时，光标消失在地图上时会无法访问附近地点

### ISSUE THREAD

**Issue by Penguin-max** [NaviHX/bupt-tour#13]
添加user，start选择本部地点，des选择沙河地点

在user从本部西门前往沙河西门时，查看user附近的地点，无输出

**Comment by NaviHX** [comment]
当进入findNearbyLoc函数时，检查内存
![image](https://user-images.githubusercontent.com/63288135/112632005-8abd2680-8e72-11eb-9484-6e6e026c06ae.png)
发现此时myUser中存在合法的User对象，但是控制台中无输出
查看该User对象的Path成员，发现其栈顶的元素为沙河校区的西门，编号为1。用于判断是否到达目的地的getDes函数在走完路径后返回-1，而对于不显示导航路径的边，getDes返回目的地编号的相反数（初始化时事先存入负值）
![image](https://user-images.githubusercontent.com/63288135/112632697-6ada3280-8e73-11eb-91ed-387b381ddedd.png)
在findNearbyLoc函数中，使用了getDes判断路径是否有剩余，沙河西门编号恰好与-1冲突，产生冲突
![image](https://user-images.githubusercontent.com/63288135/112632919-af65ce00-8e73-11eb-93f3-57a58dce1553.png)

**Comment by NaviHX** [comment]
将getDes函数用于表示非法对象的返回值更改为0x80000000
![image](https://user-images.githubusercontent.com/63288135/112636221-bee71600-8e77-11eb-92b0-115c5d8a4d4b.png)
